"""
ArbTASwapRSIV2 Strategy Package.

Generated by: almanak strat new
"""

try:
    from .strategy import ArbTASwapRSIV2Strategy
except ImportError:
    from strategy import ArbTASwapRSIV2Strategy

__all__ = [
    "ArbTASwapRSIV2Strategy",
]
